"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ensure = exports.write = exports.read = void 0;
const fs_extra_1 = require("fs-extra");
const read = (path) => (0, fs_extra_1.readFileSync)(path, { encoding: 'utf-8' });
exports.read = read;
const write = (path, content) => (0, fs_extra_1.writeFileSync)(path, content);
exports.write = write;
const ensure = (path) => (0, fs_extra_1.ensureFileSync)(path);
exports.ensure = ensure;
